FROM #MC_PROJECT#/jre8:latest

LABEL MAINTAINER="Dennis Saminathan"

ENV NEXUS_VERSION=3.22.0-02
ARG PORT=8081
## required by both run time and build time
ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk

ARG GROOVY_HOME=/usr/local/groovy-2.5.7
ARG PATH=$PATH:$GROOVY_HOME/bin

RUN apk update \
        && apk --no-cache add bash \
        && rm -rf /var/lib/apt/lists/* \
        && rm -rf /var/cache/apk/*

ADD setup/configscripts/* /home/appuser/app/
ADD setup/start.sh /home/appuser/app/start.sh
ADD setup/json/* /home/appuser/app/

RUN curl -L http://download.sonatype.com/nexus/3/nexus-$NEXUS_VERSION-unix.tar.gz --progress-bar | tar zxf -
RUN mv /nexus-$NEXUS_VERSION /home/appuser/app/


RUN chmod +x /home/appuser/app/start.sh
RUN chown -R appuser:appuser /home/appuser/data /home/appuser/app

USER appuser

CMD ["/home/appuser/app/start.sh"]
